apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullerting-ingress
  annotations:
    # Ingress Controller ������ ���� �ٸ� annotation�� ����� �� �ֽ��ϴ�.
    # �Ʒ��� �Ϲ����� Nginx Ingress Controller �����Դϴ�.
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api # '/api'�� �����ϴ� ��� ��û�� �޽��ϴ�.
            pathType: Prefix
            backend:
              service:
                name: fullerting-backend-service # ��û�� ������ ����
                port:
                  number: 8082 # ������ ��Ʈ
